### ISSUE TITLE
error_reporting level is too permissive

### ISSUE THREAD

**Issue by anton-kachurin** [bu-ist/php-test-runner#4]
**Issue:**
I created `phpunit.xml` file that starts like this:
```
<phpunit
	bootstrap="tests/bootstrap.php"
	backupGlobals="false"
	colors="true"
	convertErrorsToExceptions="true"
	convertNoticesToExceptions="true"
	convertWarningsToExceptions="true"
	beStrictAboutCoversAnnotation="true"
	>
```

I expected that all notices that my code throws would be reported as errors by `phpunit`. However, I didn't see any errors. I ran this from within the container:
```
$ php -a

php > $arr = [];
php > $arr['a'];
php > echo $arr['a'];
```

Turned out, php doesn't show any notices in this case. That's presumably because of the setting in `php.ini` that makes it to ignore notices.

**Expected behavior:**
Notices should be thrown by php and converted to exceptions when the `phpunit.xml` is configured that way

**Comment by carlosesilva** [comment]
@anton-kachurin see PR #5
It sets the `error_reporting` level to `E_ALL`, let me know if that works for you.
